feat: добавлена работа с user и item
YaminoJakkaru/java-shareit pull request #1
Opened 2023-03-08 20:16 UTC by YaminoJakkaru

2023-03-09 05:31 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара небольших замечаний, которые необходимо исправить!

2023-03-09 05:31 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/emum/Status.java
> +package ru.practicum.shareit.booking.emum;
1. `enum`, наверное
2. лучше это в пакет с каким-то осмысленным названием. так как по факту это перечислени - это объект значение, то можно его в пакет `vo` (сокращение от `value-object`).

2023-03-09 05:31 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +    private int id = 0;
Это стоит перенести в `storage`.
Если мы для реализации хранилища будем использовать работу с СУБД, а мы будем, то там удобнее использовать генерацию идентификаторов с помощью механизмов, которые предоставляет СУБД.

Здесь логика, такая же

2023-03-09 05:31 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        log.info("Добавлен предмет " + id);
Это лучше писать после добавления в классе-хранилище, а то мало ли, какая ошибка может произойти, а по логам мы будем думать, что вставка произошла

2023-03-09 05:31 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
Аналогично про идентификатор и логгирование успешных результатов

2023-03-09 05:31 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/storage/inMemory/InMemoryUserStorage.java
> +    }
Зачем?

2023-03-09 06:14 UTC, YaminoJakkaru commented on src/main/java/ru/practicum/shareit/booking/emum/Status.java
> +package ru.practicum.shareit.booking.emum;
исправлено

2023-03-09 06:14 UTC, YaminoJakkaru commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +    private int id = 0;
исправлено

2023-03-09 06:14 UTC, YaminoJakkaru commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        log.info("Добавлен предмет " + id);
исправлено

2023-03-09 06:14 UTC, YaminoJakkaru commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
исправлено

2023-03-09 06:14 UTC, YaminoJakkaru commented on src/main/java/ru/practicum/shareit/user/storage/inMemory/InMemoryUserStorage.java
> +    }
исправлено

2023-03-10 07:37 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!!!

2023-03-19 06:27 UTC, merged