Add bookings
YaminoJakkaru/java-shareit pull request #3
Opened 2023-04-01 13:59 UTC by YaminoJakkaru

2023-04-01 20:42 UTC, LexLippi requested changes
Привет!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-04-01 20:42 UTC, LexLippi commented on src/main/resources/schema.sql
> +    email VARCHAR(512)                            NOT NULL,
В RFC указано, что валидная длина электронной почты не превышает 320 символов.
https://www.rfc-editor.org/errata/eid1690

2023-04-01 20:42 UTC, LexLippi commented on src/main/resources/schema.sql
> +    requestor_id BIGINT                                  NOT NULL,
Эта колонка разве не ссылается на пользователя?

2023-04-01 20:42 UTC, LexLippi commented on src/main/resources/schema.sql
> +    is_available boolean,
Может быть `null`?

2023-04-01 20:42 UTC, LexLippi commented on src/main/resources/schema.sql
> +    text         VARCHAR(512),
лучше не называть колонки аналогично типам данных, это может привести к разным неприятным последствиям

2023-04-01 20:42 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +
Как-то многовато пробелов. Тебе не кажется?)

2023-04-01 20:42 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +    public final ItemRepository itemRepository;
Почему это `public`?

2023-04-01 20:42 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +                    .collect(Collectors.toList()));
Это плохой подход.

Пусть у тебя `m` `item`-ов, `n` `comment`-ов, `k` `booking`-ов. Алгоритмическая сложность этого метода `O(m(n+k)), а если бы ты заранее преобразовал эти коллекции в `HashMap`, то сложность была бы `O(n+m+k)`. Разница огромная

2023-04-01 20:42 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private ItemRequest request;
Необходимы ограничения на колонки, аналогичные тем, что есть в БД

2023-04-02 08:01 UTC, LexLippi requested changes
Привет!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-04-03 07:24 UTC, LexLippi requested changes
Привет!

Осталась еще пара небольших замечаний!

Желаю удачи при доработке!

2023-04-03 07:24 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        return items;
Если уж используем `Stream API`:

```java
return text.isBlank() ? List.of() : itemRepository.findItemByNameOrDescriptionContainsIgnoreCaseAndAvailableIsTrue(text, text)
                        .stream()
                        .map(Item::toItemDto)
                        .collect(Collectors.toList());
```

2023-04-03 07:24 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        itemRepository.findItemsByOwnerIdOrderByIdAsc(userId).forEach(item -> items.put(item.getId(),item.toItemDto()));
С помощью Stream API можно в одну последовательность вызовов уложить создание данного отображения

2023-04-03 12:01 UTC, YaminoJakkaru commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        return items;
исправил

2023-04-03 12:01 UTC, YaminoJakkaru commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        itemRepository.findItemsByOwnerIdOrderByIdAsc(userId).forEach(item -> items.put(item.getId(),item.toItemDto()));
исправил

2023-04-04 05:55 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2023-04-11 08:11 UTC, merged